// state list

export const GET_SCHEDULED_LIST_REQUEST='GET_SCHEDULED_LIST_REQUEST'
export const SET_SCHEDULED_LIST_REQUEST='SET_SCHEDULED_LIST_REQUEST'

//in progress

export const GET_INPROGRESS_LIST_REQUEST='GET_INPROGRESS_LIST_REQUEST'
export const SET_INPROGRESS_LIST_REQUEST='SET_INPROGRESS_LIST_REQUEST'

//complete

export const GET_COMPLETED_LIST_REQUEST='GET_COMPLETED_LIST_REQUEST'
export const SET_COMPLETED_LIST_REQUEST='SET_COMPLETED_LIST_REQUEST'

//past
export const GET_PAST_LIST_REQUEST='GET_PAST_LIST_REQUEST'
export const SET_PAST_LIST_REQUEST='SET_PAST_LIST_REQUEST'

//messages
export const SET_DASHBOARD_MESSAGES='SET_DASHBOARD_MESSAGES'

// Change status

export const CHANGE_STATUS_REQUEST='CHANGE_STATUS_REQUEST'
export const CHANGE_STATUS='CHANGE_STATUS'


// Delete
export const DELETE_APPOINTMENT="DELETE_APPOINTMENT"

//pdf

export const OPEN_PDF="OPEN_PDF"
export const SET_PDF="SET_PDF"