// state list

export const GET_STATE_LIST_REQUEST='GET_STATE_LIST_REQUEST'
export const SET_STATE_LIST_REQUEST='SET_STATE_LIST_REQUEST'
export const GET_STATE_BY_NAME_LIST_REQUEST='GET_STATE_BY_NAME_LIST_REQUEST'


//city 

export const GET_CITY_LIST_REQUEST='GET_CITY_LIST_REQUEST'
export const SET_CITY_LIST_REQUEST='SET_CITY_LIST_REQUEST'

export const GET_CITY_BY_NAME_LIST_REQUEST='GET_CITY_BY_NAME_LIST_REQUEST'

//medication

export const GET_MEDICATION_LIST_REQUEST="GET_MEDICATION_LIST_REQUEST"
export const SET_MEDICATION_LIST_REQUEST="SET_MEDICATION_LIST_REQUEST"

//country 
export const GET_COUNTRY_LIST_REQUEST="GET_COUNTRY_LIST_REQUEST"
export const SET_COUNTRY_LIST_REQUEST="SET_COUNTRY_LIST_REQUEST"
export const GET_COUNTRY_BY_NAME_LIST_REQUEST="GET_COUNTRY_BY_NAME_LIST_REQUEST"