
/** List of SYMPTOMS */
export const GET_PATIENT_DETAIL_REQUEST = 'GET_PATIENT_DETAIL_REQUEST';
export const SET_PATIENT_DETAIL_LIST_REQUEST = 'SET_PATIENT_DETAIL_LIST_REQUEST';

//Create patient
export const ADD_APPOINTMENTS = 'ADD_APPOINTMENTS';
export const ADD_APPOINTMENTS_REQUEST = 'ADD_APPOINTMENTS_REQUEST';

// get names

export const SET_DOCTORNAMES_LIST_REQUEST='SET_DOCTORNAMES_LIST_REQUEST'
export const GET_DOCTORNAMES_LIST_REQUEST='GET_DOCTORNAMES_LIST_REQUEST'
export const SET_LASTNAMES_LIST_REQUEST='SET_LASTNAMES_LIST_REQUEST'
export const GET_PATIENT_DETAIL_BY_NAME_REQUEST='GET_PATIENT_DETAIL_BY_NAME_REQUEST'

//message

export const APPOINTMENTS_MESSAGES='APPOINTMENTS_MESSAGES'
export const SET_APPOINTMENT_MESSAGES_REQUEST="SET_APPOINTMENT_MESSAGES_REQUEST"

//summary list
export const SET_SUMMARY_LIST_REQUEST="SET_SUMMARY_LIST_REQUEST"
export const GET_SUMMARY_LIST_REQUEST="GET_SUMMARY_LIST_REQUEST"