
/** List of SYMPTOMS */
export const GET_SYMPTOMS_LIST_REQUEST = 'GET_SYMPTOMS_LIST_REQUEST';
export const SET_SYMPTOMS_LIST_REQUEST = 'SET_SYMPTOMS_LIST_REQUEST';

//Create patient
export const ADD_PATIENT = 'ADD_PATIENT';
export const ADD_PATIENT_REQUEST = 'ADD_PATIENT_REQUEST';

// get names

export const SET_FIRSTNAMES_LIST_REQUEST='SET_FIRSTNAMES_LIST_REQUEST'
export const GET_FIRSTNAMES_LIST_REQUEST='GET_FIRSTNAMES_LIST_REQUEST'
export const SET_LASTNAMES_LIST_REQUEST='SET_LASTNAMES_LIST_REQUEST'
export const GET_LASTNAMES_LIST_REQUEST='GET_LASTNAMES_LIST_REQUEST'


//message handling

export const SET_PATIENTS_MESSAGES='SET_PATIENTS_MESSAGES'