export const SET_INPROGRESS_DATA_LIST_REQUEST =
  "SET_INPROGRESS_DATA_LIST_REQUEST";
export const GET_INPROGRSS_DATA_BY_NAME_LIST_REQUEST =
  "GET_INPROGRSS_DATA_BY_NAME_LIST_REQUEST";
export const POST_INPROGRESS_PROBLEM_DIAGNOSIS =
  "POST_INPROGRESS_PROBLEM_DIAGNOSIS";

export const ADD_UPDATE_MEDICATION = "ADD_UPDATE_MEDICATION";
export const MEDICATION_MESSAGES = "MEDICATION_MESSAGES";
export const ADD_UPDATE_MEDICATION_REQUEST = "ADD_UPDATE_MEDICATION_REQUEST";
// Get allproblem diagnosis
export const GET_ALL_PROBLEM_DIAGNOSIS = " GET_ALL_PROBLEM_DIAGNOSIS";
//medication detail
export const GET_MEDICATION_DETAIL_LIST_REQUEST =
  "GET_MEDICATION_DETAIL_LIST_REQUEST";
export const SET_MEDICATION_DETAIL_LIST_REQUEST =
  "SET_MEDICATION_DETAIL_LIST_REQUEST";
//physicians
export const GET_PHYSICIANS_DESCRIPTION_LIST_REQUEST="GET_PHYSICIANS_DESCRIPTION_LIST_REQUEST"
export const SET_PHYSICIANS_DESCRIPTION_LIST_REQUEST="SET_PHYSICIANS_DESCRIPTION_LIST_REQUEST"

//diagnosis
export const GET_DIAGNOSIS_LIST_REQUEST="GET_DIAGNOSIS_LIST_REQUEST";
export const SET_DIAGNOSIS_LIST_REQUEST="SET_DIAGNOSIS_LIST_REQUEST";
export const SET_INPROGRESS_PROBLEM_DIAGNOSIS="SET_INPROGRESS_PROBLEM_DIAGNOSIS"

//clear messages

export const CLEAR_MESSAGES="CLEAR_MESSAGES"

//delete medication
export const DELETE_MEDICATION="DELETE_MEDICATION"